// =============================================================
// SEED.TS — Dados padrão (fallback quando Firestore está vazio)
// =============================================================

import type { EscolaRede, ModalidadeEnsino, NivelEnsino, RegistroCargaHoraria, DicionarioInep, Turma, Professor, Disciplina, Aluno, Nota, Aviso, EquipeMembro, GaleriaItem, Depoimento, EventoCalendario } from './types';

export const SEED: Record<string, unknown> = {
  escola: {
    nome: 'Unidade Escolar Professora Edith Nair Furtado da Silva',
    cidade: 'Viana · Maranhão',
    anoLetivo: 2026,
    logomarca: '',
    whatsapp: '(98) 99999-9999',
    email: 'secretaria@edith.edu.ma.gov.br',
  },

  config: {
    sistemaFechado: false,
    dataFechamento: null,
    notaMinima: 5.0,
    bimestreAtual: 1,
  },

  turmas: [
    { id: 't01', escolaId: 'esc01', nome: '6º Ano A', turno: 'manhã', professorId: 'p01', disciplinaId: 'd01',
      modalidadeId: 'mod_fund2', nivelEnsinoId: 'niv_fund2', serie: '6º',
      isMultisseriada: false, seriesAgrupadas: [], isMultietapa: false, etapasAgrupadas: [],
      isAEE: false, tagsAEE: [], professorIds: ['p01'],
      cargaHorariaSemanal: 25, duracaoAulaMinutos: 50, ativo: true },
    { id: 't02', escolaId: 'esc01', nome: '7º Ano A', turno: 'manhã', professorId: 'p02', disciplinaId: 'd02',
      modalidadeId: 'mod_fund2', nivelEnsinoId: 'niv_fund2', serie: '7º',
      isMultisseriada: false, seriesAgrupadas: [], isMultietapa: false, etapasAgrupadas: [],
      isAEE: false, tagsAEE: [], professorIds: ['p02'],
      cargaHorariaSemanal: 25, duracaoAulaMinutos: 50, ativo: true },
    { id: 't03', escolaId: 'esc01', nome: '8º Ano A', turno: 'tarde', professorId: 'p03', disciplinaId: 'd03',
      modalidadeId: 'mod_fund2', nivelEnsinoId: 'niv_fund2', serie: '8º',
      isMultisseriada: false, seriesAgrupadas: [], isMultietapa: false, etapasAgrupadas: [],
      isAEE: false, tagsAEE: [], professorIds: ['p03'],
      cargaHorariaSemanal: 25, duracaoAulaMinutos: 50, ativo: true },
    { id: 't04', escolaId: 'esc01', nome: '8º Ano B', turno: 'tarde', professorId: 'p01', disciplinaId: 'd01',
      modalidadeId: 'mod_fund2', nivelEnsinoId: 'niv_fund2', serie: '8º',
      isMultisseriada: false, seriesAgrupadas: [], isMultietapa: false, etapasAgrupadas: [],
      isAEE: false, tagsAEE: [], professorIds: ['p01'],
      cargaHorariaSemanal: 25, duracaoAulaMinutos: 50, ativo: true },
    { id: 't05', escolaId: 'esc01', nome: '9º Ano A', turno: 'noite', professorId: 'p02', disciplinaId: 'd01',
      modalidadeId: 'mod_fund2', nivelEnsinoId: 'niv_fund2', serie: '9º',
      isMultisseriada: false, seriesAgrupadas: [], isMultietapa: false, etapasAgrupadas: [],
      isAEE: false, tagsAEE: [], professorIds: ['p02'],
      cargaHorariaSemanal: 25, duracaoAulaMinutos: 50, ativo: true },
  ] satisfies Turma[],

  professores: [
    { id: 'p01', escolaId: 'esc01', nome: 'Maria das Graças Santos', email: 'maria@escola.edu', disciplinas: ['d01','d02'], turmaIds: ['t01','t04'], ativo: true },
    { id: 'p02', escolaId: 'esc01', nome: 'José Carlos Ferreira', email: 'jose@escola.edu', disciplinas: ['d02','d03'], turmaIds: ['t02','t05'], ativo: true },
    { id: 'p03', escolaId: 'esc01', nome: 'Ana Beatriz Oliveira', email: 'ana@escola.edu', disciplinas: ['d03','d04'], turmaIds: ['t03'], ativo: true },
  ] satisfies Professor[],

  disciplinas: [
    { id: 'd01', escolaId: 'esc01', nome: 'Língua Portuguesa', icone: 'fa-book-open', cor: '#ef4444', ativo: true },
    { id: 'd02', escolaId: 'esc01', nome: 'Matemática', icone: 'fa-calculator', cor: '#3b82f6', ativo: true },
    { id: 'd03', escolaId: 'esc01', nome: 'Ciências', icone: 'fa-flask', cor: '#10b981', ativo: true },
    { id: 'd04', escolaId: 'esc01', nome: 'História', icone: 'fa-landmark', cor: '#f59e0b', ativo: true },
    { id: 'd05', escolaId: 'esc01', nome: 'Geografia', icone: 'fa-earth-americas', cor: '#8b5cf6', ativo: true },
    { id: 'd06', escolaId: 'esc01', nome: 'Arte', icone: 'fa-palette', cor: '#ec4899', ativo: true },
    { id: 'd07', escolaId: 'esc01', nome: 'Educação Física', icone: 'fa-futbol', cor: '#f97316', ativo: true },
    { id: 'd08', escolaId: 'esc01', nome: 'Língua Inglesa', icone: 'fa-language', cor: '#6366f1', ativo: true },
    { id: 'd09', escolaId: 'esc01', nome: 'Ensino Religioso', icone: 'fa-star', cor: '#a855f7', ativo: true },
  ] satisfies Disciplina[],

  alunos: [
    { id: 'a01', nome: 'Ana Carolina Souza', matricula: '2026001', cpf: '111.111.111-11', turmaId: 't01', escolaId: 'esc01', ativo: true,
      dataNascimento: '2015-03-22', sexo: 'F', corRaca: 'parda', codigoINEP: null, certidaoNascimento: '123456',
      necessidadesEspeciais: [], deficiencia: null, transporte: 'nenhum', zona: 'urbana' },
    { id: 'a02', nome: 'Bruno Henrique Lima', matricula: '2026002', cpf: '222.222.222-22', turmaId: 't01', escolaId: 'esc01', ativo: true,
      dataNascimento: '2015-07-15', sexo: 'M', corRaca: 'branca', codigoINEP: null, certidaoNascimento: '234567',
      necessidadesEspeciais: [], deficiencia: null, transporte: 'nenhum', zona: 'urbana' },
    { id: 'a03', nome: 'Carla Fernanda Costa', matricula: '2026003', cpf: '333.333.333-33', turmaId: 't01', escolaId: 'esc01', ativo: true,
      dataNascimento: '2015-01-10', sexo: 'F', corRaca: 'preta', codigoINEP: null, certidaoNascimento: '345678',
      necessidadesEspeciais: ['baixa_visao'], deficiencia: 'visual', transporte: 'escolar_publico', zona: 'rural' },
  ] satisfies Aluno[],

  notas: [
    { id: 'n001', alunoId: 'a01', disciplinaId: 'd01', b1: 8.5, b2: 7.0, b3: null, b4: null },
    { id: 'n002', alunoId: 'a01', disciplinaId: 'd02', b1: 6.0, b2: 5.5, b3: null, b4: null },
    { id: 'n003', alunoId: 'a02', disciplinaId: 'd01', b1: 9.0, b2: 8.5, b3: null, b4: null },
  ] satisfies Nota[],

  frequencia: [],

  diario: [
    { id: 'di001', turmaId: 't01', professorId: 'p01', data: '2026-03-15', conteudo: 'Aula sobre interpretação de texto — Gêneros textuais', anotacao: 'Turma participativa, boa interação.' },
  ],

  atividades: [
    { id: 'at001', turmaId: 't01', professorId: 'p01', titulo: 'Interpretação de Texto — Conto Moderno', descricao: 'Ler o conto e responder às questões de interpretação.', dataPrazo: '2026-04-20', pontos: 10, tipo: 'escrita', dataCriacao: '2026-04-01', ativo: true },
  ],

  aee: [
    { id: 'aee01', alunoId: 'a02', professorId: 'p01', necessidade: 'Dislexia', planoAtendimento: 'Atividades com fonemas.', observacoes: 'Evolução positiva.', dataCriacao: '2026-02-10' },
  ],

  avisos: [
    { id: 'av001', titulo: 'Início do 2º Bimestre', corpo: 'O 2º bimestre começa em 14 de abril.', tipo: 'info', autoria: 'diretor', dataCriacao: '2026-04-01', turmaId: null, ativo: true },
  ] satisfies Aviso[],

  equipe: [
    { id: 'eq01', nome: 'Mariana Costa', cargo: 'Diretora', descricao: 'Gestão escolar.', icone: 'fa-crown', cor1: '#d97706', cor2: '#f59e0b', ativo: true, ordem: 1 },
  ] satisfies EquipeMembro[],

  galeria: [
    { id: 'gal01', titulo: 'Sala de Aula', icone: 'fa-chalkboard-user', corFundo1: '#dbeafe', corFundo2: '#bfdbfe', corIcone: '#2563eb', ativo: true, ordem: 1 },
  ] satisfies GaleriaItem[],

  depoimentos: [
    { id: 'dep01', texto: 'O portal facilitou muito.', nome: 'Maria Silva', cargo: 'Mãe de Aluno', cor1: '#059669', cor2: '#10b981', ativo: true, ordem: 1 },
  ] satisfies Depoimento[],

  escolas_rede: [
    { id: 'esc01', slug: 'ueedithnair', nome: 'U.E. Professora Edith Nair Furtado da Silva', nomeAbreviado: 'U.E. Edith Nair',
      codigoINEP: '21045780', endereco: 'Rua Principal, 100 - Centro', cidade: 'Viana', estado: 'MA',
      telefone: '(98) 99999-9999', email: 'secretaria@edith.edu.ma.gov.br', diretorNome: 'Administrador',
      whatsapp: '(98) 99999-9999', logomarca: '',
      tipo: 'urbana', modalidades: ['fundamental_ii'], turnosFuncionamento: ['manhã','tarde'],
      capacidade: 500, anoLetivo: 2026,
      dependenciaAdm: 'municipal', localizacaoDiferenciada: 'nao_se_aplica',
      infraestrutura: { agua: 'rede_publica', esgoto: 'rede_publica', energia: 'rede_publica',
        internet: true, bandaLarga: true, acessibilidade: true, quadraEsportiva: true,
        biblioteca: true, laboratorioInformatica: true, laboratorioCiencias: false,
        cozinha: true, refeitorio: true, banheiroPNE: true, salaRecursos: false },
      sistemaFechado: false, dataFechamento: null, notaMinima: 5.0, bimestreAtual: 1,
      ativa: true, criadoEm: '2026-01-15' },
    { id: 'esc02', slug: 'uemanoel', nome: 'U.E. Manoel Beckman', nomeAbreviado: 'U.E. Manoel Beckman',
      codigoINEP: '21045798', endereco: 'Av. Brasil, 450 - Bairro Novo', cidade: 'Viana', estado: 'MA',
      telefone: '(98) 98888-8888', email: 'contato@manoel.edu.ma.gov.br', diretorNome: 'José Ferreira',
      whatsapp: '(98) 98888-8888', logomarca: '',
      tipo: 'urbana', modalidades: ['fundamental_ii'], turnosFuncionamento: ['manhã','tarde','noite'],
      capacidade: 350, anoLetivo: 2026,
      dependenciaAdm: 'municipal', localizacaoDiferenciada: 'nao_se_aplica',
      infraestrutura: { agua: 'rede_publica', esgoto: 'fossa', energia: 'rede_publica',
        internet: true, bandaLarga: false, acessibilidade: false, quadraEsportiva: true,
        biblioteca: false, laboratorioInformatica: true, laboratorioCiencias: false,
        cozinha: true, refeitorio: false, banheiroPNE: false, salaRecursos: false },
      sistemaFechado: false, dataFechamento: null, notaMinima: 5.0, bimestreAtual: 1,
      ativa: true, criadoEm: '2026-02-01' },
    { id: 'esc03', slug: 'uesaojoao', nome: 'U.E. São João Batista', nomeAbreviado: 'U.E. São João',
      codigoINEP: '21045801', endereco: 'Estrada do Interior, Km 12', cidade: 'Viana', estado: 'MA',
      telefone: '(98) 97777-7777', email: 'contato@saojoao.edu.ma.gov.br', diretorNome: 'Ana Oliveira',
      whatsapp: '(98) 97777-7777', logomarca: '',
      tipo: 'rural', modalidades: ['fundamental_ii'], turnosFuncionamento: ['manhã'],
      capacidade: 120, anoLetivo: 2026,
      dependenciaAdm: 'municipal', localizacaoDiferenciada: 'area_assentamento',
      infraestrutura: { agua: 'poco_artesiano', esgoto: 'fossa', energia: 'rede_publica',
        internet: false, bandaLarga: false, acessibilidade: false, quadraEsportiva: false,
        biblioteca: false, laboratorioInformatica: false, laboratorioCiencias: false,
        cozinha: true, refeitorio: false, banheiroPNE: false, salaRecursos: false },
      sistemaFechado: false, dataFechamento: null, notaMinima: 5.0, bimestreAtual: 1,
      ativa: true, criadoEm: '2026-02-10' },
  ] satisfies EscolaRede[],

  modalidades_ensino: [
    { id: 'mod_infantil', codigo: 'educacao_infantil', nome: 'Educação Infantil',
      registroCargaHoraria: 'manual_diario', cargaHorariaAnualMinima: 800, diasLetivosMinimos: 200,
      usaNotasBimestrais: false, usaCamposExperiencia: true, permiteMultisseriada: true, ativo: true },
    { id: 'mod_fund1', codigo: 'fundamental_i', nome: 'Ensino Fundamental I (Anos Iniciais)',
      registroCargaHoraria: 'grade_fixa', cargaHorariaAnualMinima: 800, diasLetivosMinimos: 200,
      usaNotasBimestrais: true, usaCamposExperiencia: false, permiteMultisseriada: true, ativo: true },
    { id: 'mod_fund2', codigo: 'fundamental_ii', nome: 'Ensino Fundamental II (Anos Finais)',
      registroCargaHoraria: 'grade_fixa', cargaHorariaAnualMinima: 800, diasLetivosMinimos: 200,
      usaNotasBimestrais: true, usaCamposExperiencia: false, permiteMultisseriada: false, ativo: true },
    { id: 'mod_eja', codigo: 'eja', nome: 'Educação de Jovens e Adultos (EJA)',
      registroCargaHoraria: 'grade_fixa', cargaHorariaAnualMinima: 640, diasLetivosMinimos: 200,
      usaNotasBimestrais: true, usaCamposExperiencia: false, permiteMultisseriada: false, ativo: true },
    { id: 'mod_medio', codigo: 'ensino_medio', nome: 'Ensino Médio',
      registroCargaHoraria: 'grade_fixa', cargaHorariaAnualMinima: 1000, diasLetivosMinimos: 200,
      usaNotasBimestrais: true, usaCamposExperiencia: false, permiteMultisseriada: false, ativo: true },
    { id: 'mod_medio_tec', codigo: 'ensino_medio_tecnico', nome: 'Ensino Médio Técnico Integrado',
      registroCargaHoraria: 'grade_fixa', cargaHorariaAnualMinima: 1000, diasLetivosMinimos: 200,
      usaNotasBimestrais: true, usaCamposExperiencia: false, permiteMultisseriada: false, ativo: true },
    { id: 'mod_aee', codigo: 'aee', nome: 'Atendimento Educacional Especializado (AEE)',
      registroCargaHoraria: 'manual_diario', cargaHorariaAnualMinima: 0, diasLetivosMinimos: 0,
      usaNotasBimestrais: false, usaCamposExperiencia: false, permiteMultisseriada: false, ativo: true },
    { id: 'mod_ativcomp', codigo: 'atividades_complementares', nome: 'Atividades Complementares',
      registroCargaHoraria: 'manual_diario', cargaHorariaAnualMinima: 0, diasLetivosMinimos: 0,
      usaNotasBimestrais: false, usaCamposExperiencia: false, permiteMultisseriada: false, ativo: true },
  ] satisfies ModalidadeEnsino[],

  niveis_ensino: [
    { id: 'niv_bercario', modalidadeId: 'mod_infantil', nome: 'Berçário (Creche)', sigla: 'BRC',
      subniveis: ['M1','M2','M3'], idadeMinimaMeses: 0, idadeMaximaMeses: 23, dataCorte: '03-31', ordemExibicao: 1, ativo: true },
    { id: 'niv_creche_g', modalidadeId: 'mod_infantil', nome: 'Creche — Grupos', sigla: 'CRG',
      subniveis: ['G1','G2','G2.2','G2.3'], idadeMinimaMeses: 12, idadeMaximaMeses: 35, dataCorte: '03-31', ordemExibicao: 2, ativo: true },
    { id: 'niv_preescola', modalidadeId: 'mod_infantil', nome: 'Pré-Escola', sigla: 'PRE',
      subniveis: ['G3','G3.4','G3.5','G4','G5'], idadeMinimaMeses: 36, idadeMaximaMeses: 71, dataCorte: '03-31', ordemExibicao: 3, ativo: true },
    { id: 'niv_fund1', modalidadeId: 'mod_fund1', nome: 'Anos Iniciais (1º ao 5º)', sigla: 'AI',
      subniveis: ['1º Ano','2º Ano','3º Ano','4º Ano','5º Ano'], idadeMinimaMeses: 72, idadeMaximaMeses: 131, dataCorte: '03-31', ordemExibicao: 1, ativo: true },
    { id: 'niv_fund2', modalidadeId: 'mod_fund2', nome: 'Anos Finais (6º ao 9º)', sigla: 'AF',
      subniveis: ['6º','7º','8º','9º'], idadeMinimaMeses: 132, idadeMaximaMeses: 179, dataCorte: '03-31', ordemExibicao: 1, ativo: true },
    { id: 'niv_eja1', modalidadeId: 'mod_eja', nome: 'EJA — Etapa 1 (1º ao 3º)', sigla: 'EJ1',
      subniveis: ['1º Ano','2º Ano','3º Ano'], idadeMinimaMeses: 180, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 1, ativo: true },
    { id: 'niv_eja2', modalidadeId: 'mod_eja', nome: 'EJA — Etapa 2 (4º e 5º)', sigla: 'EJ2',
      subniveis: ['4º Ano','5º Ano'], idadeMinimaMeses: 180, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 2, ativo: true },
    { id: 'niv_eja3', modalidadeId: 'mod_eja', nome: 'EJA — Etapa 3 (6º e 7º)', sigla: 'EJ3',
      subniveis: ['6º Ano','7º Ano'], idadeMinimaMeses: 180, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 3, ativo: true },
    { id: 'niv_eja4', modalidadeId: 'mod_eja', nome: 'EJA — Etapa 4 (8º e 9º)', sigla: 'EJ4',
      subniveis: ['8º Ano','9º Ano'], idadeMinimaMeses: 180, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 4, ativo: true },
    { id: 'niv_medio', modalidadeId: 'mod_medio', nome: 'Ensino Médio (1ª a 3ª)', sigla: 'EM',
      subniveis: ['1ª Série','2ª Série','3ª Série'], idadeMinimaMeses: 180, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 1, ativo: true },
    { id: 'niv_medio_tec', modalidadeId: 'mod_medio_tec', nome: 'Ensino Médio Técnico', sigla: 'EMT',
      subniveis: ['1ª Série','2ª Série','3ª Série'], idadeMinimaMeses: 180, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 1, ativo: true },
    { id: 'niv_aee', modalidadeId: 'mod_aee', nome: 'Sala de Recursos AEE', sigla: 'AEE',
      subniveis: [], idadeMinimaMeses: null, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 1, ativo: true },
    { id: 'niv_ativcomp', modalidadeId: 'mod_ativcomp', nome: 'Atividades Complementares', sigla: 'ATC',
      subniveis: [], idadeMinimaMeses: null, idadeMaximaMeses: null, dataCorte: null, ordemExibicao: 1, ativo: true },
  ] satisfies NivelEnsino[],

  registro_carga_horaria: [
    { id: 'rch01', escolaId: 'esc01', turmaId: 't01', data: '2026-02-10',
      blocos: [
        { inicio: '07:30', fim: '09:00', atividade: 'Aula de Matemática', minutos: 90 },
        { inicio: '09:20', fim: '10:50', atividade: 'Aula de Português', minutos: 90 },
        { inicio: '11:00', fim: '11:50', atividade: 'Aula de Ciências', minutos: 50 },
      ],
      totalMinutos: 230, professorId: 'p01', observacao: '', criadoEm: '2026-02-10' },
    { id: 'rch02', escolaId: 'esc01', turmaId: 't01', data: '2026-02-11',
      blocos: [
        { inicio: '07:30', fim: '09:00', atividade: 'Aula de História', minutos: 90 },
        { inicio: '09:20', fim: '10:50', atividade: 'Aula de Geografia', minutos: 90 },
        { inicio: '11:00', fim: '11:50', atividade: 'Educação Física', minutos: 50 },
      ],
      totalMinutos: 230, professorId: 'p01', observacao: '', criadoEm: '2026-02-11' },
  ] satisfies RegistroCargaHoraria[],

  dicionario_inep: [
    { id: 'inep_cor_0', tabela: 'cor_raca', codigo: 0, descricao: 'Não declarada', chave: 'nao_declarada' },
    { id: 'inep_cor_1', tabela: 'cor_raca', codigo: 1, descricao: 'Branca', chave: 'branca' },
    { id: 'inep_cor_2', tabela: 'cor_raca', codigo: 2, descricao: 'Preta', chave: 'preta' },
    { id: 'inep_cor_3', tabela: 'cor_raca', codigo: 3, descricao: 'Parda', chave: 'parda' },
    { id: 'inep_cor_4', tabela: 'cor_raca', codigo: 4, descricao: 'Amarela', chave: 'amarela' },
    { id: 'inep_cor_5', tabela: 'cor_raca', codigo: 5, descricao: 'Indígena', chave: 'indigena' },
    { id: 'inep_sexo_1', tabela: 'sexo', codigo: 1, descricao: 'Masculino', chave: 'M' },
    { id: 'inep_sexo_2', tabela: 'sexo', codigo: 2, descricao: 'Feminino', chave: 'F' },
    { id: 'inep_dep_1', tabela: 'dependencia_adm', codigo: 1, descricao: 'Federal', chave: 'federal' },
    { id: 'inep_dep_2', tabela: 'dependencia_adm', codigo: 2, descricao: 'Estadual', chave: 'estadual' },
    { id: 'inep_dep_3', tabela: 'dependencia_adm', codigo: 3, descricao: 'Municipal', chave: 'municipal' },
    { id: 'inep_dep_4', tabela: 'dependencia_adm', codigo: 4, descricao: 'Privada', chave: 'privada' },
    { id: 'inep_loc_1', tabela: 'localizacao', codigo: 1, descricao: 'Urbana', chave: 'urbana' },
    { id: 'inep_loc_2', tabela: 'localizacao', codigo: 2, descricao: 'Rural', chave: 'rural' },
    { id: 'inep_agua_1', tabela: 'agua', codigo: 1, descricao: 'Rede Pública', chave: 'rede_publica' },
    { id: 'inep_agua_2', tabela: 'agua', codigo: 2, descricao: 'Poço Artesiano', chave: 'poco_artesiano' },
    { id: 'inep_agua_3', tabela: 'agua', codigo: 3, descricao: 'Cacimba/Cisterna', chave: 'cacimba' },
    { id: 'inep_agua_4', tabela: 'agua', codigo: 4, descricao: 'Rio/Igarapé', chave: 'rio' },
    { id: 'inep_agua_5', tabela: 'agua', codigo: 5, descricao: 'Inexistente', chave: 'inexistente' },
    { id: 'inep_esg_1', tabela: 'esgoto', codigo: 1, descricao: 'Rede Pública', chave: 'rede_publica' },
    { id: 'inep_esg_2', tabela: 'esgoto', codigo: 2, descricao: 'Fossa Séptica', chave: 'fossa' },
    { id: 'inep_esg_3', tabela: 'esgoto', codigo: 3, descricao: 'Inexistente', chave: 'inexistente' },
    { id: 'inep_def_1', tabela: 'deficiencia', codigo: 1, descricao: 'Cegueira', chave: 'cegueira' },
    { id: 'inep_def_2', tabela: 'deficiencia', codigo: 2, descricao: 'Baixa Visão', chave: 'baixa_visao' },
    { id: 'inep_def_3', tabela: 'deficiencia', codigo: 3, descricao: 'Surdez', chave: 'surdez' },
    { id: 'inep_def_4', tabela: 'deficiencia', codigo: 4, descricao: 'Def. Auditiva', chave: 'auditiva' },
    { id: 'inep_def_5', tabela: 'deficiencia', codigo: 5, descricao: 'Surdocegueira', chave: 'surdocegueira' },
    { id: 'inep_def_6', tabela: 'deficiencia', codigo: 6, descricao: 'Def. Física', chave: 'fisica' },
    { id: 'inep_def_7', tabela: 'deficiencia', codigo: 7, descricao: 'Def. Intelectual', chave: 'intelectual' },
    { id: 'inep_def_8', tabela: 'deficiencia', codigo: 8, descricao: 'Def. Múltipla', chave: 'multipla' },
    { id: 'inep_def_9', tabela: 'deficiencia', codigo: 9, descricao: 'TEA (Autismo)', chave: 'tea' },
    { id: 'inep_def_10', tabela: 'deficiencia', codigo: 10, descricao: 'Altas Habilidades', chave: 'altas_habilidades' },
    { id: 'inep_transp_0', tabela: 'transporte', codigo: 0, descricao: 'Não utiliza', chave: 'nenhum' },
    { id: 'inep_transp_1', tabela: 'transporte', codigo: 1, descricao: 'Escolar Público Municipal', chave: 'escolar_publico' },
    { id: 'inep_transp_2', tabela: 'transporte', codigo: 2, descricao: 'Escolar Público Estadual', chave: 'escolar_estadual' },
    { id: 'inep_transp_3', tabela: 'transporte', codigo: 3, descricao: 'Particular', chave: 'particular' },
    { id: 'inep_sit_1', tabela: 'situacao_aluno', codigo: 1, descricao: 'Aprovado', chave: 'aprovado' },
    { id: 'inep_sit_2', tabela: 'situacao_aluno', codigo: 2, descricao: 'Reprovado', chave: 'reprovado' },
    { id: 'inep_sit_3', tabela: 'situacao_aluno', codigo: 3, descricao: 'Cursando', chave: 'cursando' },
    { id: 'inep_sit_4', tabela: 'situacao_aluno', codigo: 4, descricao: 'Transferido', chave: 'transferido' },
    { id: 'inep_sit_5', tabela: 'situacao_aluno', codigo: 5, descricao: 'Deixou de Frequentar', chave: 'desistente' },
    { id: 'inep_sit_6', tabela: 'situacao_aluno', codigo: 6, descricao: 'Falecido', chave: 'falecido' },
  ] satisfies DicionarioInep[],

  eventos_calendario: [
    { id: 'ev01', titulo: 'Início do 2º Bimestre', data: '2026-04-14', tipo: 'academico', cor: '#2563eb', descricao: 'Início das aulas do 2º bimestre letivo.' },
    { id: 'ev02', titulo: 'Reunião de Pais', data: '2026-04-22', tipo: 'reuniao', cor: '#d97706', descricao: 'Reunião de pais e mestres no auditório às 19h.' },
  ] satisfies EventoCalendario[],
};
